### ISSUE TITLE
Many LFW images cannot find labels from the lfw_race_dict.json

### ISSUE THREAD

**Issue by BerenLuthien** [usc-sail/mica-race-from-face#2]
Hi
Thanks for the project.
Question: 
Regarding

>  "lfw_race_dict.json: mapping of race for identities in the LFW dataset"

Only about 25% LFW images (downloaded from http://vis-www.cs.umass.edu/lfw/) have labels from lfw_race_dict.json
Would you share some light ?, e.g., where did you get this lfw_race_dict.json file ? Is there a complete label list for all LFW images ?
Thanks a lot

**Comment by krsna6** [comment]
The lfw_race_dict.json  contains only labels for people of single race who are available in the LFW database. I have excluded multiracial labels because of the nature of my experiments. The identities in LFW that haven't been labeled implies that they are either missing (we do not have labels for these) or they can be multiracial labels which can looked up in the actor_race.txt
